namespace DomainCentric.BuildingBlocks.Ddd.Tactical;

/// <summary>
/// Marker interface for identity value objects.
/// </summary>
/// <remarks>
/// <para>
/// An identifier is a value object whose only job is to identify an <see cref="IEntity{TSelf, TId}"/>
/// or aggregate root. It has no identity of its own — two identifiers with the same underlying
/// value are the same identifier — so it is compared by value, never by reference.
/// </para>
/// <para>
/// <b>Recommended implementation:</b> a <c>readonly record struct</c>. It is immutable, has
/// value-based equality and hashing generated by the compiler, and allocates nothing.
/// </para>
/// <example>
/// <code>
/// public readonly record struct ProductId(Guid Value) : IId
/// {
///     public static ProductId New() => new(Guid.NewGuid());
/// }
/// </code>
/// </example>
/// </remarks>
public interface IId
{
}
